jobs:
- job: BuildMacOS
  pool:
    vmImage: 'macOS 10.14'

  timeoutInMinutes: 360

  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/macos_script
    name: main
    displayName: 'Build and test'
- job: BuildLinux
  pool:
    vmImage: 'ubuntu-16.04'

  timeoutInMinutes: 360

  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/linux_script
    name: main
    displayName: 'Build and test'
- job: BuildWindowsMSVC
  pool:
    vmImage: 'vs2017-win2016'

  timeoutInMinutes: 360

  steps:
  - script: |
      git clone https://github.com/msys2/msys2-ci-base.git $(Pipeline.Workspace)\msys64
      $(Pipeline.Workspace)\msys64\usr\bin\rm -rf $(Pipeline.Workspace)\msys64\.git
      set PATH=$(Pipeline.Workspace)\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      $(Pipeline.Workspace)\msys64\usr\bin\pacman --noconfirm -Syyuu
    displayName: Install and Update MSYS2
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/windows_script_msvc.bat
    name: main
    displayName: 'Build and test'
- job: BuildWindowsMSYS
  pool:
    vmImage: 'vs2017-win2016'

  timeoutInMinutes: 360

  steps:
  - script: |
      git clone https://github.com/msys2/msys2-ci-base.git $(Pipeline.Workspace)\msys64
      $(Pipeline.Workspace)\msys64\usr\bin\rm -rf $(Pipeline.Workspace)\msys64\.git
      set PATH=$(Pipeline.Workspace)\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      $(Pipeline.Workspace)\msys64\usr\bin\pacman --noconfirm -Syyuu
    displayName: Install and Update MSYS2
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: |
      set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      set "SRCROOT=%cd%"
      $(Pipeline.Workspace)\msys64\usr\bin\bash -lc "bash ${SRCROOT}/ci/azure/windows_msys_script"
    name: main
    displayName: 'Build and test'
    env:
      MSYSTEM: MINGW64
      CHERE_INVOKING: yes

- job: UpdateDownloadPage
  dependsOn:
  - BuildMacOS
  - BuildLinux
  - BuildWindowsMSVC
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  strategy:
    maxParallel: 1
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    macos_tarball: $[ dependencies.BuildMacOS.outputs['main.tarball'] ]
    macos_shasum: $[ dependencies.BuildMacOS.outputs['main.shasum'] ]
    macos_bytesize: $[ dependencies.BuildMacOS.outputs['main.bytesize'] ]
    linux_tarball: $[ dependencies.BuildLinux.outputs['main.tarball'] ]
    linux_shasum: $[ dependencies.BuildLinux.outputs['main.shasum'] ]
    linux_bytesize: $[ dependencies.BuildLinux.outputs['main.bytesize'] ]
    windows_tarball: $[ dependencies.BuildWindowsMSVC.outputs['main.tarball'] ]
    windows_shasum: $[ dependencies.BuildWindowsMSVC.outputs['main.shasum'] ]
    windows_bytesize: $[ dependencies.BuildWindowsMSVC.outputs['main.bytesize'] ]
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/update_download_page
    displayName: 'Update download page'
